### ISSUE TITLE
Student session review reveals user _id

### ISSUE THREAD

**Issue by turnergarrow** [qlicker/qlicker#165]
By including the user _id in the url, you expose it to the user. It also means that anyone who sees that _id can see that student's session results. This is a huge problem, as it exposes every student's results to anyone who is looking over their shoulder.

**Comment by ryanmartinneutrino** [comment]
I'm not too worried about this, as the _id by itself should not be sensitive. As long as one has to be logged in as the user to pull up the page to review the results, we should be fine. Definitely, we want to make sure that when the response data is published, it is only the fraction that corresponds to the logged in user if they are a student.
