### ISSUE TITLE
Check that upload of large pictures (profile and other) are correctly handled

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#189]
At minimum, user should get a notice that "max file upload size is XXMB" if limit is exceeded. Probably that size should be in settings.json.

If we allow the initial uploaded to be ~8MB (typical cell phone picture), how easy is it to reduce its file size before storing it on S3? There are plugins to do so, just not sure if they exist on the JS side or have to be on the S3 side.

**Comment by ryanmartinneutrino** [comment]
The max size should probably be in the admin settings, rather than settings.json, as suggested above.

We should also scale the picture down when it gets dragged into an editor, so that it doesn't look crazy.

The best is probably to look for something that transforms the image on its way to S3, which I am sure is do able.

**Comment by turnergarrow** [comment]
I'll start working on this one now. I'll add the max size to admin settings and figure out a way to resize the image if it's too big. I'll also add the ability to generate thumbnails if the image is a profile image, so that it's easier to load 200 of them.
