### ISSUE TITLE
Session copy should reset questions

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#239]
Currently, if you copy a session (duplicate), then the duplicate seems to remember attempts and setting as to whether a question should show stats, etc; that should all be reset when the session is copied.

**Comment by ReckoningReckoner** [comment]
Is this still an issue? I cannot replicate. The logic in sessions.copy in sessions.js doesn't seem to copy over the responses.

**Comment by ryanmartinneutrino** [comment]
Yes, I think I fixed that in the big commit, but resetting sessionOptions to a default when copying questions.
