### ISSUE TITLE
Forbid signup with no name

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#302]
Not sure if should require only one of First, Last, probably should require both.

**Comment by ReckoningReckoner** [comment]
To add to this:
- Blank names are rendered as "undefined"
- The error message to the user is that accounts need a "first name or email". This is untrue, all you need is an email in order for qlicker to work.

**Comment by ryanmartinneutrino** [comment]
Yes, we should change this so that the name is required, and editable at least by admin

**Comment by ryanmartinneutrino** [comment]
The name is now editable in profile view.
