### ISSUE TITLE
Add student to course displays the wrong message

### ISSUE THREAD

**Issue by ReckoningReckoner** [qlicker/qlicker#341]
When looking at the course details as a professor, the message "Add TA to ..." shows up when clicking the "Add Student" button.

**Comment by ReckoningReckoner** [comment]
Not sure if this is the wrong message, or if the student gets added as a TA.

**Comment by ryanmartinneutrino** [comment]
You're right, the text in the render() method of AddStudentModal was just copied and pasted from the Add TA modal; it should be changed (both the title and the prompt of the modal).

**Comment by ReckoningReckoner** [comment]
This was fixed in #343
