### ISSUE TITLE
New question types to add

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#386]
- straight-up upload of a picture
- numerical question (give tolerance)

**Comment by PfeifferH** [comment]
Might also be worth adding poll type question where no incorrect answer

**Comment by ryanmartinneutrino** [comment]
Not sure if already implement by multi-select, but could do it that way if MS requires at least one to be correct. By setting the points for a question to 0, one can effectively make a polling question, since it won't count towards participation or grade if the points = 0.
