### ISSUE TITLE
Copy questions from session to library

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#401]
When  questions are created directly in a session (the most convenient way to create them), they are not automatically copied to the question library. Should have a button in the session editor (or in the sessionListItem menu from the course page), that allows all questions to be exported at once to the question library (currently, each question can be copied over individually)

**Comment by PfeifferH** [comment]
To extend this, when questions are created in the question library, and edited in a session, the original questions are no longer accessible.

**Comment by ryanmartinneutrino** [comment]
When a question is imported from the library into a session, a copy of the question is made for the session (so that multiple people can take a question from the library and edit it in the session). The original question in the library should not be affected - if it is, then this is a bug.
