### ISSUE TITLE
Bad course name formatting in the top menu bar is course has the name ABC ####

### ISSUE THREAD

**Issue by zjevik** [qlicker/qlicker#562]
If a course has three character department code (i.e. ABC 1234) then the top menu bar will display ABC1 234 instead of the correct ABC 1234. This is the only place where it's displayed like this.

Also, I believe the issue #251 is not corrected - admin (if it's a prof for a class) cannot see Question Library in the top bar.

**Comment by ryanmartinneutrino** [comment]
Fixed by PR #586
