### ISSUE TITLE
Inaccurate stats and AnswerDistribution for Multi Select questions

### ISSUE THREAD

**Issue by etenoch** [qlicker/qlicker#77]
Files Involved: QuestionDisplay.jsx & AnswerDistribution.jsx

Pre-conditions:
- Multi select question
- student has submitted a response with multiple options
- Attempt > 1

Bug: Graph does not show correct number of responses for answers with multiple selected

**Comment by ReckoningReckoner** [comment]
I cannot reproduce this anymore. I believe it was fixed in: e41a714fe6e8b
